version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: >
      sh -c "
        poetry run python backend/manage.py makemigrations &&
        poetry run python backend/manage.py migrate &&
        poetry run python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    # environment:
    #   - POSTGRES_DB=tracks
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_HOST=db
    #   - POSTGRES_PORT=5432
    #   - DATABASE_URL=postgres://postgres:postgres@db:5432/tracks
    depends_on:
      - db
    networks:
      - traks_network

  dash:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8050:8050"
    depends_on:
      - django
    networks:
      - traks_network

  db:
    image: postgres:latest
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: tracks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traks_network

volumes:
  postgres_data:
networks:
  traks_network:
    driver: bridge
